import streamlit as st
import pandas as pd
import plotly.express as px

# 1. Page Configuration / Configuración de la página
st.set_page_config(page_title="Sales Performance Dashboard", layout="wide")

# 2. Professional Header / Encabezado Profesional
st.title("📊 Interactive Sales Performance Dashboard")
st.markdown("""
### Data Visualization for Process Optimization
This application displays a clean visual representation of sales records, 
ensuring **data integrity** and providing actionable insights for the team.
""")

# 3. Data Loading / Carga de datos
# Using the cleaned dataset generated by your 03_limpieza_datos.py script
df = pd.read_csv('ventas_limpias.csv')

# 4. Sidebar Filters / Filtros Laterales (Interactividad)
st.sidebar.header("Filter Options")
st.sidebar.info("Select specific collaborators to update the visual reports.")

vendedor = st.sidebar.multiselect(
    "Select Collaborator:",
    options=df["nombre_limpio"].unique(),
    default=df["nombre_limpio"].unique()
)

# Filtering logic
df_selection = df.query("nombre_limpio == @vendedor")

# 5. Visualizations / Visualizaciones con Plotly
# Column layout for a professional look
left_column, right_column = st.columns(2)

with left_column:
    st.subheader("Sales by Collaborator")
    fig_bar = px.bar(
        df_selection,
        x='nombre_limpio',
        y='monto',
        color='monto',
        color_continuous_scale='Viridis',
        template='plotly_dark',
        labels={'nombre_limpio': 'Collaborator', 'monto': 'Total Amount ($)'}
    )
    st.plotly_chart(fig_bar, use_container_width=True)

with right_column:
    st.subheader("Data Preview (Structured Table)")
    st.dataframe(df_selection, use_container_width=True)

# 6. Technical Footer / Pie de página técnico
st.markdown("---")
st.write("Built by **Belén Abigail Acuña** | Systems Engineering Student")